### ISSUE TITLE
Interactivity broken with low-zoom in multiple browsers (incorrect mouse coordinate calc?)

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1220]
It seems the mouse coordinate calculation is broken on non-100% zooms - I can especially see it on 90% (see below)

* Ensure your browser's zoom is at 100%
* Open standard [bar chart example](https://vega.github.io/editor/#/examples/vega/bar-chart)
* Test that hover effect works on mouseover
* hit ctrl + '-' to zoom to 25% of the original  (make the graph smaller)
* Test that the hover effect still works ok
* Reload the page (Ctrl+R)
* Observe that graph hover effect no longer works

Works partially:
* zoom to 90% of the original
* Reload the page
* Notice that hover effect is only working on the left portion of each bar, not the whole bar

found in both the latest Chrome and Firefox

Tester file attached. [no-interactive.html.gz](https://github.com/vega/vega/files/1873580/no-interactive.html.gz)

**Comment by nyurik** [comment]
thanks @jheer !  i just hope we can have unit tests for all these cases - it would be horrible to hunt those down again after something unrelated changes in Vega.  Do you think its possible to test for these cases?  Google's new headless browser might really help.

On a separate note, I wonder if this is related to the thin white lines i still sometimes see when mouseovering on some graphs - #985

**Comment by jheer** [comment]
Fixed in v3.3.0, via the aforementioned handling of pixel ratio values.

**Comment by nyurik** [comment]
@jheer i just checked with the editor running 3.3.0 - the issue is still there.

**Comment by nyurik** [comment]
Seems like this was an issue with the Vega editor not updating dependencies.  I wonder if package.json needs to be updated to use `^1.2.3` format for dependencies. Without it, I suspect that npm and yarn will assume that any minor/patch version would do, and won't update local dependency if it's good enough.

**Comment by jheer** [comment]
I'm not sure how the editor manages release builds, as I didn't write the code for the current version. In any case, I think the build system should upgrade all dependencies to the latest package.json-compatible versions by default. Patch versions often have important bug fixes, but it seems unreasonable to have to update the stated dependencies in order to track those. In any case, I tend to be religious about deleting `node_modules` as part of my release process...
