### ISSUE TITLE
Nest transform generate signal does not update data

### ISSUE THREAD

**Issue by nyurik** [vega/vega#1243]
[The code in PR](https://github.com/vega/vega/pull/1242) seems to indicate that setting `generate` parameter for the `nest` transform via a signal does not regenerate the data pipeline.

Repo:  open PR's vega code, and click the checkbox.  Also try to set the initial value to false, and click the checkbox.

**Comment by jheer** [comment]
Thanks! I fixed this issue as part of a larger refactoring of hierarchy management and treelink generation. The lastest is in master in the [vega-hierarchy](https://github.com/vega/vega-hierarchy) repo. However, the updates include changes to the parameter signatures of some of the transforms, so I'm batching them for a later Vega release that includes some more significant changes for, among other things, parity with D3 v5.

**Comment by nyurik** [comment]
@jheer changes to the parameter signatures means a breaking change for all existing users of Vega graphs. Please make it backward compatible, otherwise we won't be able to use it - imagine breaking tens of thousands of graphs with the upgrade -- noone would get the new version, as the upgrade cost of a big platform instantly skyrockets.

**Comment by nyurik** [comment]
P.S. Vega could still show a warning when older parameter style is being used, e.g. "param X has been renamed to param Y for trtansform Z, please update your graph".  Or just support both names.  Thx for all your work on this!

**Comment by jheer** [comment]
Yes, I'm well aware of the negative effects of non-backwards-compatible changes. Don't worry 😁

**Comment by jheer** [comment]
Fixed in v4.0.0-rc.1.
