### ISSUE TITLE
force collide change after interaction

### ISSUE THREAD

**Issue by mattijn** [vega/vega#981]
I was playing with a dorling cartogram visualization for my own situation and had issues with the speed (its slow) and with the force collide transform. The location of the symbols are shifting while panning and scrolling for the first time.  My use case is [there](https://vega.github.io/editor/#/gist/vega/mattijn/770ca5c0e498d946301725eec04c7057)
 
For the force collide part, I created a minimum working example where the issue can be reproduced (I think) using the existing Dorling Cartogram [example](https://vega.github.io/editor/#/examples/vega/dorling-cartogram), I changed the encode part of the `marks` / `circle` section to the following:

```
      "encode": {
        "update": {
          "size": {"scale": "size", "field": "rate"},
          "fill": {"scale": "color", "field": "rate"},
          "stroke": {"value": "white"},
          "strokeWidth": {"value": 1.5},
          "x": {"field": "centroid[0]"},
          "y": {"field": "centroid[1]"},
          "tooltip": {"signal": "'Obesity Rate: ' + format(datum.rate, '.1%')"}
        },
        "hover": {
          "stroke": {"value": "black"}
        }
      },
```
I only included a stroke color change on a hover action and the behaviour becomes as follow:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5186265/29368058-f547e910-829e-11e7-9b6b-f03fe2c15a14.gif)

At the locations where the symbols are overlapping and the collide transform becomes active the symbols are shifting. And the shift is only happening after the first hover operation, by the second/third/nth hover operation the location of the symbol stays the same.

**Comment by jheer** [comment]
Thanks for raising the issue. There are a couple things happening here.

1. The force transform does not re-run the simulation by default when there are only modified tuples (so only the "re-centering" of the points to the computed centroid is occurring). To enable updates, add the parameter `"restart": true` to the transform. However, in this case you will experience movement of the states that you most likely do not want. I recommend moving the `force` transform out of the mark definition and into the source data transforms (in other words, precomputing the x,y positions and then leaving them constant). That way you can perform interactive updates without worrying about interactions with the force transform.
2. This example reveals a bug in pulse propagation during visual encoding, which is manifested here by the text labels staying put while the circles move. I'll investigate a fix later...

**Comment by jheer** [comment]
The pulse propagation bug has been fixed by commits to vega-encode and vega-view, which will be released in Vega v3.0.2.

**Comment by mattijn** [comment]
The online [editor ](https://vega.github.io/editor/#/examples/vega/dorling-cartogram)is at version 3.0.2 but the described behaviour is still present
